### ISSUE TITLE
Object rotate

### ISSUE THREAD

**Issue by linhnguyen106** [TheMaggieSimpson/Vuforia559_jPCT-AE#1]
Can you explain to me why : 
        cylinder.rotateX(90.0f);
I've tried to load my own object, but texture apply is wrong position, can you help me ?

**Comment by TheMaggieSimpson** [comment]
@linhnguyen106
1. That line is only an example on how to rotate the object on x-axis. You can ignore that line and do your own transformation (scaling, rotating, translating).
2. Texture position is attached to the object. If you can view your object and its texture correctly in a 3D viewer (like Autocad, Blender, MeshLab, or whatever), I think you shouldn't have this problem. Have you tried to viewed your object and its respective texture in a 3D viewer?

**Comment by linhnguyen106** [comment]
@TheMaggieSimpson thank for your quickly reply, yes I've viewed my .obj file in X-code and it looks good  , but when I load it by jpct ae, it is bad : [https://api.asm.skype.com/v1/objects/0-neu-d4-c47271b2de37d3a3236efb9722672763/views/imgpsh_fullsize](url).

**Comment by TheMaggieSimpson** [comment]
@linhnguyen106 your link does not work. Can you also upload your object and its texture online, and share me the link?

**Comment by linhnguyen106** [comment]
@TheMaggieSimpson I just use your sample with my obj file from download link [http://153.121.60.192/aradmin/uploads/3d/GAZ-AA_boxOBJ.zip](url) and the code I used to load obj file 
and this is how it display in my device : [https://drive.google.com/open?id=0BwjAe9s3yI2ickJJVDN0d2dxR3M](url)
please copy and paste the url

```
`private Object3D loadModel(InputStream  objStream,InputStream  mtlStream, float scale) {
            Object3D[] model = Loader.loadOBJ(objStream, mtlStream, scale);

            Object3D o3d = new Object3D(0);
            o3d = Object3D.mergeAll(model);
            o3d.setCenter(SimpleVector.ORIGIN);
            o3d.rotateX((float)( -.5*Math.PI));
            o3d.rotateMesh();
            o3d.translateMesh();
            o3d.setRotationMatrix(new Matrix());
return o3d;
}`
```

**Comment by TheMaggieSimpson** [comment]
@linhnguyen106 you're using multiple textures. Are you sure you already added all textures to the TextureManager correctly? Put all of them in 1 folder inside your assets folder, then make a for loop to make sure you add all of them to the TextureManager. You don't need to call "setTexture("textureName")" after the loop, since jpct-ae will automatically map them to the object.

```
for ( String filename : getAssets().list("yourFolderNames") ) {
    if ( !TextureManager.getInstance().containsTexture(filename) ) {
        Texture t = new Texture(getAssets().open("yourFolderNames/"+filename));
        TextureManager.getInstance().addTexture(filename, t);
    }
}
```

Hope it helps :)

**Comment by linhnguyen106** [comment]
@TheMaggieSimpson all the texture files are also in the zip file . Because I want the object will be changed by the time so my code is getting the zip file and save into sdcard. I've added those textures, but the Textures by some how apply not correct position as you can see at my screen shot. Here are the code for adding texture 

```
`for(String s : textTureFiles){
                        String[] temp = s.split("/");
                        String imageName = temp[temp.length-1];
                        Log.e("render", "texture :" +imageName);
                        if(!TextureManager.getInstance().containsTexture(imageName)){
                            com.threed.jpct.Texture texture;
                            try {
                                texture = new com.threed.jpct.Texture(new FileInputStream(s));
                                TextureManager.getInstance().addTexture(imageName, texture);

                            } catch (FileNotFoundException e) {
                                // TODO Auto-generated catch block
                                e.printStackTrace();
                            }

                        }
                    }` 

```

**Comment by TheMaggieSimpson** [comment]
@linhnguyen106 have you tried to use "getAssets.open()", instead of "new FileInputStream()"? I created myself a small testcase using your object and its textures, and everything works fine for me. The textures mapped nicely to the object.

**Comment by linhnguyen106** [comment]
@TheMaggieSimpson many thank for your help . Because I have alot of ImageTarget so I can not store the texture file in Assets folder . It need to be downloaded and save in sdcard .

**Comment by TheMaggieSimpson** [comment]
@linhnguyen106 ok, I see. So it's not a jpct-ae problem anymore. Now it's all about how to read/open images from sd-card in android correctly, because I think some of your textures are not added to the TextureManager. Sorry, can't help any further.

**Comment by linhnguyen106** [comment]
@TheMaggieSimpson thank you very much. I owe you a beer :)
