### ISSUE TITLE
one model how to use multiple texture ?

### ISSUE THREAD

**Issue by ushang000** [TheMaggieSimpson/Vuforia559_jPCT-AE#2]
hi
one model how to use multiple texture?
i have one obj model contain house and grass ,
how can i setTexture use house texture and grass texture for this obj model ?

**Comment by TheMaggieSimpson** [comment]
This is not an issue of integrating Vuforia with jPCT-AE. So please refer to their wiki (http://www.jpct.net/wiki/index.php) for more information about texture in jPCT-AE.
As long as you have added the textures correctly, it should be mapped automatically.
